const ENDPOINT = 'https://script.google.com/macros/s/AKfycbzumuymFpbbD8NSl5PUw_crFlne8ZRN0UL1npwGEIzirse8G-lKYzdh6aJaga1pcEmzOQ/exec';
const roles = ['Sound','Stream','Lighting','Stage'];
const tasks = {
 Lighting:[
  'Run large extension cord from Aftercare / separate DB board','Connect lighting power to intended school/Aftercare supply','Connect stage lights through lighting chain','Connect Blinder 1','Connect Head Bangers 1, 2, 3 and 4 in sequence','Connect Head Banger 4 to Blinder 2','Connect hazer','Connect stage lights through Speaker Light 1 and Speaker Light 2','Confirm Blinder 1 and Blinder 2 have power','Confirm all Head Bangers have power','Load the previous show','Test lights: no random flashing','Test transitions switch smoothly','Confirm colours match correctly'],
 Stream:[
  'Camera 1: power connected','Camera 1: HDMI connected','Camera 1 angle checked','Camera 2: power connected','Camera 2: HDMI connected','Camera 2 angle checked','ATEM connected and powered','All required ATEM cables connected','Laptop connected and powered','All required laptop cables connected','Sound desk power connected','Black signal cable connected','White signal cable connected','Mac switched on','Projector tested','Stream tested','Spotify tested through sound'],
 Sound:[
  'Stage Rack connected and powered','Drum Rack connected and powered','Ethernet connected to Stage Rack','Ethernet connected to Drum Rack','Speaker 1 connected to Stage Rack Channel 1','Speaker 2 connected to Stage Rack Channel 2','Sub signal / daisy chain connected','Left and right signal lines connected','Front-of-House Fill signal connected','Crowd mic Left and Right lines run','SP talkback mic line run','Stage Rack reel outlet 1 powers Speaker Stand 1','Long kettle cord powers Front-of-House Fill','Stage Rack reel outlet 2 split kettle powers Sub 2 and Sub 3','Hall reel powers Speaker Stand 2, Sub 1 and line arrays','Speaker Stand 1 line arrays and Sub 4 powered from Stage Rack reel extension'],
 Stage:[
  'Check band requirements for the week','Position instruments according to requirements','Confirm instrument layout','Drums: kick connected','Drums: snare connected','Drums: Tom 1 connected','Drums: Tom 2 connected','Drums: floor tom connected','Drums: cymbal mic connected','Drum ME connected','Keys run stereo into DI','Keys sustain pedal connected','Keys power connected','Keys ME run to PoE switch','Peter: stand set up when applicable','Peter: ME connected when applicable','Rob: wireless receiver set up','Rob: receiver output to pedal','Rob: pedal output to DI','Rob: DI connected to Stage Rack','Rob: ME run to PoE switch','Rob: extension power run','Tenmiel: wireless receiver set up','Tenmiel: XLR from receiver to guitar position','Tenmiel: Scarlett and laptop connected','Tenmiel: Scarlett output to DI','Tenmiel: DI connected to Stage Rack','Tenmiel: ME run to PoE switch','Tenmiel: extension power run']
};
const shared={
 'Stream|Lighting':['Kids: TVs placed in respective classrooms','Kids: stations set up in front of classrooms','Kids: check-in station set up','Dream Team check-in station set up','Dream Team Welcome TV set up','Left-side hall chairs set with consistent four-tile spacing','Assist with taping after core duties'],
 'Sound|Stage':['Right-side hall chairs set with consistent four-tile spacing'],
 'ALL':['Final integrated testing completed','Keys tested through left and right speakers and subs','Drums tested through subs','Relevant soft switches unmuted','Band faders up','Drum faders up','Main faders up']
};
const rolesEl=document.querySelector('#roles'), lists=document.querySelector('#checklists');
roles.forEach(r=>{rolesEl.insertAdjacentHTML('beforeend',`<label class="role"><input type="checkbox" value="${r}"> ${r}</label>`)});
document.querySelector('#date').value=new Date().toISOString().slice(0,10);
rolesEl.addEventListener('change',render); lists.addEventListener('change',updateProgress);
function selected(){return [...rolesEl.querySelectorAll('input:checked')].map(x=>x.value)}
function render(){lists.innerHTML=''; const sel=selected(); sel.forEach(role=>addSection(role,tasks[role],false)); if(sel.some(x=>['Stream','Lighting'].includes(x))) addSection('Shared — Kids, Chairs & Taping',shared['Stream|Lighting'],true); if(sel.some(x=>['Sound','Stage'].includes(x))) addSection('Shared — Chairs',shared['Sound|Stage'],true); if(sel.length) addSection('Final Testing',shared.ALL,true); updateProgress()}
function addSection(title,items,isShared){const unique=[...new Set(items)]; const id=title.replace(/[^a-z0-9]/gi,'-'); lists.insertAdjacentHTML('beforeend',`<section class="card checklist" data-section="${title}"><div class="section-title"><h2>${title}</h2>${isShared?'<span class="shared">SHARED</span>':''}</div>${unique.map((t,i)=>`<label class="task"><input type="checkbox" data-task="${encodeURIComponent(t)}"><span>${t}</span></label>`).join('')}</section>`)}
function updateProgress(){const all=[...document.querySelectorAll('.checklist input')],done=all.filter(x=>x.checked).length; document.querySelector('#progressText').textContent=`${done} / ${all.length} complete`; const p=document.querySelector('#progress');p.max=Math.max(all.length,1);p.value=done}
document.querySelector('#submit').addEventListener('click',async()=>{const name=document.querySelector('#name').value,sel=selected(),all=[...document.querySelectorAll('.checklist input')],incomplete=all.filter(x=>!x.checked); if(!name)return alert('Select your name.'); if(!sel.length)return alert('Select at least one role.'); if(incomplete.length && !confirm(`${incomplete.length} checks are incomplete. Submit and flag them for Keanan anyway?`))return; const payload={name,email:document.querySelector('#email').value||'',date:document.querySelector('#date').value,roles:sel,notes:document.querySelector('#notes').value,submittedAt:new Date().toISOString(),checks:all.map(x=>({section:x.closest('.checklist').dataset.section,task:decodeURIComponent(x.dataset.task),complete:x.checked}))}; if(!ENDPOINT){document.querySelector('#status').textContent='Checklist is working. Google Sheet endpoint still needs to be connected.'; console.log(payload); return;} try{document.querySelector('#submit').disabled=true; await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)}); window.location.replace('success.html');}catch(e){document.querySelector('#status').textContent='Submission failed. Please try again.';}finally{document.querySelector('#submit').disabled=false}});
