const ENDPOINT='https://script.google.com/macros/s/AKfycbzumuymFpbbD8NSl5PUw_crFlne8ZRN0UL1npwGEIzirse8G-lKYzdh6aJaga1pcEmzOQ/exec';
let submissions=[],activeMonth='';
function jsonp(params={}){return new Promise((resolve,reject)=>{const cb=`setupHistory_${Date.now()}_${Math.floor(Math.random()*100000)}`,s=document.createElement('script');const t=setTimeout(()=>{cleanup();reject(new Error('Request timed out'))},15000);function cleanup(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{cleanup();if(!d||d.ok===false)return reject(new Error(d?.error||'Request failed'));resolve(d)};const q=new URLSearchParams({...params,callback:cb});s.src=`${ENDPOINT}?${q}`;s.onerror=()=>{cleanup();reject(new Error('Could not reach Apps Script'))};document.body.appendChild(s)})}
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const monthKey=d=>String(d).slice(0,7);
function monthLabel(k){const [y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('en-ZA',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function dateLabel(d){return new Intl.DateTimeFormat('en-ZA',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`))}
function pct(v){const n=parseInt(String(v||'').replace('%',''),10);return Number.isFinite(n)?n:0}
function renderMonths(){const ms=[...new Set(submissions.map(x=>monthKey(x.setupDate)).filter(Boolean))].sort().reverse();const el=document.querySelector('#months');if(!ms.length){el.innerHTML='<p class="muted">No setup submissions yet.</p>';return}if(!activeMonth||!ms.includes(activeMonth))activeMonth=ms[0];el.innerHTML=ms.map(m=>`<button class="month-btn ${m===activeMonth?'active':''}" data-month="${m}">${esc(monthLabel(m))}</button>`).join('');el.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{activeMonth=b.dataset.month;renderMonths();renderMonth()})}
function renderMonth(){const content=document.querySelector('#historyContent'),rows=submissions.filter(x=>monthKey(x.setupDate)===activeMonth),by={};rows.forEach(r=>(by[r.setupDate]??=[]).push(r));const dates=Object.keys(by).sort().reverse();content.innerHTML=dates.length?dates.map(d=>renderDate(d,by[d])).join(''):'<section class="card"><p class="muted">No submissions for this month.</p></section>';content.querySelectorAll('[data-verify-date]').forEach(b=>b.onclick=()=>verifySetup(b.dataset.verifyDate,b))}
function renderDate(date,rows){const people=[...new Set(rows.map(r=>r.name).filter(Boolean))],roles=[...new Set(rows.flatMap(r=>String(r.roles||'').split(',').map(x=>x.trim()).filter(Boolean)))],avg=rows.length?Math.round(rows.reduce((s,r)=>s+pct(r.completion),0)/rows.length):0,issues=rows.filter(r=>String(r.notes||'').trim()||String(r.incompleteChecks||'').trim()),verified=rows.length&&rows.every(r=>r.setupLeadVerified==='Yes'),verifiedBy=rows.find(r=>r.verifiedBy)?.verifiedBy||'Keanan',verifiedAt=rows.find(r=>r.verifiedAt)?.verifiedAt||'',leadNotes=rows.find(r=>r.leadNotes)?.leadNotes||'';return `<section class="card history-date"><div class="section-title"><div><p class="eyebrow">${esc(monthLabel(monthKey(date)).toUpperCase())}</p><h2>${esc(dateLabel(date))}</h2></div><span class="pill">${verified?'VERIFIED':'NOT VERIFIED'}</span></div><div class="summary-grid"><div class="stat"><strong>${people.length}</strong><span>People</span></div><div class="stat"><strong>${roles.length}/4</strong><span>Roles covered</span></div><div class="stat"><strong>${avg}%</strong><span>Avg. completion</span></div><div class="stat"><strong>${issues.length}</strong><span>Submissions with issues</span></div></div><p><strong>Roles:</strong> ${esc(roles.join(', ')||'None')}</p><div class="submission-list">${rows.map(renderSubmission).join('')}</div><div class="verification"><h3>Setup Lead verification</h3>${verified?`<p class="muted">Verified by ${esc(verifiedBy)}${verifiedAt?` · ${esc(verifiedAt)}`:''}</p>`:'<p class="muted">This setup has not been verified yet.</p>'}<label>Lead notes<textarea id="lead-notes-${date}" rows="3" placeholder="Optional notes for this setup">${esc(leadNotes)}</textarea></label><button type="button" data-verify-date="${date}">${verified?'Update verification':'Verify this setup'}</button><p id="verify-status-${date}" class="muted"></p></div></section>`}
function renderSubmission(r){const checks=Array.isArray(r.checks)?r.checks:[],notes=String(r.notes||'').trim(),incomplete=String(r.incompleteChecks||'').trim();return `<details class="submission"><summary><span><strong>${esc(r.name)}</strong><small>${esc(r.roles||'No role')}</small></span><span>${esc(r.completion||'0%')}</span></summary>${notes?`<div class="issue-text"><strong>Notes:</strong> ${esc(notes)}</div>`:''}${incomplete?`<div class="issue-text"><strong>Incomplete:</strong> ${esc(incomplete)}</div>`:''}<div class="check-results">${checks.length?checks.map(c=>`<div class="check-result ${c.complete?'done':'missing'}"><span>${c.complete?'✓':'✕'}</span><div><strong>${esc(c.section||'')}</strong><p>${esc(c.task||'')}</p></div></div>`).join(''):'<p class="muted">No checklist detail saved.</p>'}</div></details>`}
async function verifySetup(date,button){const status=document.querySelector(`#verify-status-${date}`),notes=document.querySelector(`#lead-notes-${date}`).value.trim();button.disabled=true;status.textContent='Saving verification…';try{const r=await jsonp({action:'verify',date,verifiedBy:'Keanan',notes});status.textContent=`Verified ${r.updated||0} submission(s).`;await loadHistory(false)}catch(e){console.error(e);status.textContent='Verification failed. Please try again.'}finally{button.disabled=false}}
async function loadHistory(showLoading=true){const loading=document.querySelector('#loading'),status=document.querySelector('#historyStatus');if(showLoading)loading.style.display='';status.textContent='';try{const r=await jsonp({action:'history'});submissions=r.submissions||[];renderMonths();renderMonth()}catch(e){console.error(e);status.textContent='Could not load setup history.';document.querySelector('#historyContent').innerHTML=''}finally{loading.style.display='none'}}
loadHistory();
